import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Box } from "@chakra-ui/react";
import { Navbar } from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster"
import { SessionProvider } from "next-auth/react"
import { Provider as ChakraProvider } from "@/components/ui/provider"
import { AuthProvider } from "@/contexts/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SessionProvider> 
          <AuthProvider>
          <ChakraProvider>
              <Navbar />
            <Box as={"main"}>
            {children}
            </Box>
            <Toaster />
          </ChakraProvider>
          </AuthProvider>
        </SessionProvider>
      </body>
    </html>
  )
}