import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider"
import { Box } from "@chakra-ui/react";
import { Navbar } from "@/components/Navbar";
import { Toaster, toaster } from "@/components/ui/toaster"
import { AuthProvider } from "@/contexts/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <AuthProvider>
          <Navbar />
          <Box as={"main"}>{children}</Box>
          <Toaster />
          </AuthProvider>
        </Provider>
      </body>
    </html>
  )
}